[package]
name = "csr-server"
version = "0.1.0"
edition = "2021"

[dependencies]
csr-protocol = { path="../csr-protocol" }
env_logger="0.11"
log = "0.4"
thiserror = "1.0"
tonic = { version = "0.12", features=["transport"] }
tonic-web = "0.12"
tokio = { version = "1", features=["full"] }
