[package]
name = "csr-client"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
csr-protocol = { path="../csr-protocol" }
clap = { version = "4.5", features = ["derive"] }
env_logger = "0.11"
futures = "0.3"
log = "0.4"
tokio = { version = "1", fatures = ["full"] }
